// Generated by CoffeeScript 1.3.1
(function() {
  var _server;

  _server = require('../lib/server.js');

  exports.start = function(http_port) {
    var server;
    server = new _server.Server;
    return server.startHTTP(http_port, function() {
      return console.log('TinyQuest server started');
    });
  };

  this.start();

}).call(this);
