// Generated by CoffeeScript 1.3.1
(function() {
  var _plot;

  _plot = require('../lib/plot.js');

  this.Map = (function() {

    Map.name = 'Map';

    function Map(width, height, plot_string) {
      var plot;
      this.width = width;
      this.height = height;
      this.plot_string = plot_string;
      if (this.plot_string) {
        this.plots = (function() {
          var _i, _len, _ref, _results;
          _ref = this.plot_string;
          _results = [];
          for (_i = 0, _len = _ref.length; _i < _len; _i++) {
            plot = _ref[_i];
            _results.push(new _plot.Plot(plot));
          }
          return _results;
        }).call(this);
      }
    }

    Map.prototype.plot = function(x, y) {
      if (y != null) {
        if (this.plots != null) {
          return this.plots[x * this.width + y];
        }
      } else {
        return this.plots[x];
      }
    };

    Map.prototype.render = function() {
      var plot, s, _i, _len, _ref;
      s = "<div class=\"map\">";
      _ref = this.plots;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        plot = _ref[_i];
        s += plot.render();
      }
      return s += "</div>";
    };

    return Map;

  })();

}).call(this);
