// Generated by CoffeeScript 1.3.1
(function() {
  var fs, http, path, url;

  http = require('http');

  fs = require('fs');

  url = require('url');

  path = require('path');

  this.Server = (function() {

    Server.name = 'Server';

    function Server() {}

    Server.constructor = function() {};

    Server.prototype.startHTTP = function(http_port, callback) {
      var port, requestHandler;
      port = parseInt(process.env.PORT) || http_port || 5000;
      requestHandler = function(request, response) {
        var filename, uri;
        uri = url.parse(request.url).pathname;
        filename = path.join(process.cwd(), './assets/index.html');
        response.writeHead(200, {
          'Content-Type': 'text/html'
        });
        return fs.readFile(filename, function(error, content) {
          response.write(content);
          return response.end();
        });
      };
      this.httpServer = http.createServer(requestHandler);
      return this.httpServer.listen(Number(port), function() {
        return callback();
      });
    };

    Server.prototype.stop = function() {
      return this.httpServer.close();
    };

    return Server;

  })();

}).call(this);
