// Generated by CoffeeScript 1.3.1
(function() {

  this.View = (function() {

    View.name = 'View';

    function View(map) {
      this.map = map;
    }

    View.prototype.render = function() {
      return "<div class=\"view\">" + (this.map.render()) + "</div>";
    };

    return View;

  })();

}).call(this);
